# Generated by Django 2.1.4 on 2018-12-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('taskName', models.CharField(max_length=254)),
                ('taskID', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1024)),
                ('priority', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'taskEasyDB',
            },
        ),
    ]
