# Generated by Django 2.1.4 on 2018-12-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskEasyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='description',
        ),
        migrations.AlterModelTable(
            name='tasks',
            table='Tasks',
        ),
    ]
