# Generated by Django 2.1.4 on 2018-12-16 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskEasyApp', '0002_auto_20181216_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024),
            preserve_default=False,
        ),
    ]
